### ISSUE TITLE
formio: Name/Email Contact Creation/Follower not working for Internal Users

### ISSUE THREAD

**Issue by walkerblackwell** [novacode-nl/odoo-formio#109]
singleton error is raised when matching a form contact email/name with an internal user for follow and report emails.

Odoo v13

regards
Walker

**Comment by bobslee** [comment]
@walkerblackwell I could reproduce this issue and should be solved now (version 13, 14).
Please could you test and close this if solved?

I also improved by **Scheduling an Activity (on Form)** if multiple Partners found with same email submitted in the Form.
See screeshot...

**Requirement:** 
In order to use this feature, configure the Activity User in the Form Builder (tab: Components API).

![image](https://user-images.githubusercontent.com/328803/104813310-b1bf0280-5808-11eb-88c8-d8359c734e31.png)

**Comment by bobslee** [comment]
@walkerblackwell Could you confirm whether this is solved?

**Comment by walkerblackwell** [comment]
Hey, I have not yet verified but I will when I have the time,

cheers!
Walker

**Comment by bobslee** [comment]
Hi @walkerblackwell could you test and report pls? Or you agree I'll close this issue?

**Comment by walkerblackwell** [comment]
tested and works now
