### ISSUE TITLE
What are these versions and are they latest?

### ISSUE THREAD

**Issue by sy-github** [novacode-nl/odoo-formio#132]
![image](https://user-images.githubusercontent.com/12111755/110258955-0d05a980-7f9d-11eb-9a2b-1c05a170da94.png)

Hi, when I install I can see above listed versions. Are they official versions? Can I update to get latest versions? I clicked Check and Register available versions , but nothing happen

**Comment by bobslee** [comment]
Hi, some guidance we to consider.

1. Yes indeed, those are official releases/versions from https://github.com/formio/formio.js
2. I still need to fix the sort/ordering of the `Version` fields in the `Settings` and `Form` views. See related: https://github.com/novacode-nl/odoo-formio/issues/127
3. In order to update to the latest version(s), you need to "download and install", a feature explained below.

Hope this clarifies. Let me know if still questions or remarks.

### How to - Download and install versions

**1. Open the view GitHub releases (tags), shown in screenshot below.**

![image](https://user-images.githubusercontent.com/328803/110298354-ce034280-7ff4-11eb-8d41-778cfe5803a3.png)

**2. Click the button `Download and install`.. which opens a pop-up wizard to confirm and execute this.**

![image](https://user-images.githubusercontent.com/328803/110298509-f55a0f80-7ff4-11eb-9d14-d047c9980cf8.png)

**Comment by bobslee** [comment]
@sy-github Improvement has been solved/implemented now (see: #127)
Thanks for notifying!
Please close this issue if ok.

**Comment by sy-github** [comment]
@bobslee thanks for the instruction. I downloaded a newer version and installed now. Should I also have an extra step, which is to create a version and link it to the newly downloaded js css files? Can you add instructions to this step too so all readers can benefit?

**Comment by bobslee** [comment]
@sy-github I think you mean these assets (CSS, JS), which are already present after the _"Download and install"_ action.
Shown in the Version its 2nd tab (Assets).

I guess it would even be possible to add additional CSS, but didn't tried that in a production/live situation yet.

![image](https://user-images.githubusercontent.com/328803/110329765-54337f00-801d-11eb-8bda-1f18592387e6.png)

**Comment by sy-github** [comment]
@bobslee I've installed 4.12.7:
![image](https://user-images.githubusercontent.com/12111755/110331437-074caa00-8017-11eb-89bd-5fec62021c2b.png)
However, the versions list hasn't it:
![image](https://user-images.githubusercontent.com/12111755/110331524-1e8b9780-8017-11eb-81c4-9e7ae67394e7.png)

So do I need to manually add a version to link to the installed 4.12.7?

**Comment by bobslee** [comment]
Please check again.. I see it's in the list. 

Also update the Formio module. I pushed improvements for the version selection/dropdown in the Form Builder.

**Comment by sy-github** [comment]
@bobslee my bad. Thanks a lot.
