### ISSUE TITLE
Uncaught ReferenceError: Formio is not defined at App.createBuilder (app.js:37:23)

### ISSUE THREAD

**Issue by systemcare01** [novacode-nl/odoo-formio#191]
Found  Formiojs was removed, trying to move back still cannot work, any work around solution?

**Comment by bobslee** [comment]
Need more info. 

Which odoo version?

Which steps you undertake?

Is this occurring while upgrading an odoo version?

**Comment by bobslee** [comment]
Add screenshot(s) would also help. 
First enable the debug assets.

**Comment by systemcare01** [comment]
Thanks for quick response.
I am using odoo 15 CE,
I am trying to create builder.
Below is screenshot.
![image](https://user-images.githubusercontent.com/109518746/179753026-33b39aab-7ba7-4088-8266-ef2f921352f0.png)

**Comment by systemcare01** [comment]
is it because cannot choose formio.js version? I click the dropdown list and nothing inside, just created one with name V1.
![image](https://user-images.githubusercontent.com/109518746/179753930-8632632b-03f3-4026-9c71-37303b19857d.png)

**Comment by bobslee** [comment]
Apparently the UI of the module (on v15) ain't intuitive yet.

Since v15 the module doesn't ship any formio.js library versions anymore.
You need to download and install one - shown in screenshot below.
After "Download  & Install", you're able to select a version in the Form Builder.

Does this work for you?

![image](https://user-images.githubusercontent.com/328803/179760951-e725c785-e14a-4726-947d-a375da94a8c5.png)

**Comment by bobslee** [comment]
Hi,

I just released v.9.24 of the `formio` module.
This fixes and improves the Version issue in the Builder.

When you download and upgrade, it should already work,
But better test first !

See commit (changes): https://github.com/novacode-nl/odoo-formio/commit/a6c25a43f21c3b93bf3cb9f1bcb99b710a2eeb75

**Comment by systemcare01** [comment]
Thanks a lot, works after install formiojs v4.14.7, at beginning, I installed v5.0.0-m.13, encounter error FormioUtils is not defined, look like formio.js issue.
