### ISSUE TITLE
formio: Dummy is an invalid version ... (according to odoo.log)

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-formio#206]
According to `odoo.log`:

```
... INFO odoo odoo.modules.loading: loading formio/data/formio_version_data.xml 

... WARNING ... py.warnings: PATH/lib/python3.10/site-packages/pkg_resources/__init__.py:116:
PkgResourcesDeprecationWarning: Dummy is an invalid version and will not be supported in a future release
```

Try to reproduce this, so it can be fixed.
Or check the reasoning behind this warning.

**Comment by skaag** [comment]
I'm experiencing the same thing, while installing in Odoo 15.0.

**Comment by bobslee** [comment]
@skaag thanks for sharing.
I noticed the warning a while ago, but can't remember the circumstances anymore (my bad).

Please could you provide more info (OS, Python version, Docker?), or do you have any suggestions?
I need to reproduce somehow.

Because the warning doesn't occur on:
- Python 3.8, 3.9
- OS: Linux (eg NixOS)
- Odoo.sh platform

**Comment by BT-jcolmeiro** [comment]
Hi, I'm getting this error at install in an automated CI with debian buster and python 3.7 and it totally fails initialization of DB:

Adding logs if it helps you:

**Comment by BT-jcolmeiro** [comment]
I think this has to be with python setuptools version installed. If < 66 you pass with a warning if >= 66 you get an error. so <66 must be pined to be able to use this approach or rework this dummy version thing to a standarized version must be made. 
ref: [https://github.com/pypa/setuptools/issues/3772](https://github.com/pypa/setuptools/issues/3772)

**Comment by bobslee** [comment]
@BT-jcolmeiro Thanks for the info and suggestion. 
I'm not able to reproduce that setup (packages).

I wonder whether it's just an unfortunate choice in this version (module data) naming. 

Please could you try with a different name (also xmlid), eg: `formio_default_version` or `formio_install_version`.

Thanks!

**Comment by BT-jcolmeiro** [comment]
Hi @bobslee I tried what you suggested but still the same. Right now I identified the actual problem and several solutions so you can decide what is better for project.

**Context**: since setuptools version 66, PEP440 strict version identifiers are enforced and that is incompatible with form.io js library versions. Eg. form.io version: "4.15.0-rc.13" is not PEP440 compliant so it should be: "4.15.0rc13". "Dummy" is not a PEP440 compilant version, 0.0.0 does

**Why is code failing?**: at [formio_version.py](https://github.com/novacode-nl/odoo-formio/blob/ff2b3a9f345919067b81d6f8dd1e83346f9c3102/formio/models/formio_version.py#L58) you have a method to update/set versions sequence

`
from pkg_resources import parse_version
...
    def _update_versions_sequence(self):
        ...
        **names = sorted(names, key=parse_version)**
        ...
`
And there you use a method "parse_version" from package pkg_resources as key for the sorting that now expects a PEP440 compilant version.

**Solution:**

1. easy solution would be to remove key=parse_version from sorted so no more problems with PEP440 versions. It keeps reordering sequence OK just with a normal .sorted()

2. mid solution would be to use a package like [pip parver](https://pypi.org/project/parver/) to normalize version just before sorting.

3. full solution should be to adopt PEP440 and integrate a parse & normalice for names of formio.verision records, store js version as a another field and do migration scripts for ongoing databases.

Regards.

**Comment by bobslee** [comment]
Hi @BT-jcolmeiro Thanks for the extensive analysis and suggestion!
I shall work on the solution, probably this week.
Keep you posted!

**Comment by BT-jcolmeiro** [comment]
Hi @bobslee not at all! I can do a PR for solution 1 or 2 and maybe for 3 with more time if you want me to. But whatever suites you!

**Comment by bobslee** [comment]
Hi @BT-jcolmeiro, I just pushed a change to `15.0` and `14.0`.

For now I removed the `parse_version` from the `sorted`.
Unitl there's a better solution, the `formio.version` records are sorted naturally, with its rarities:
```
5.0.0-m.16
5.0.0-m.14
5.14.9
5.14.13-rc.9
4.14.12
```

About your 2nd and 3rd suggestion:
2. I don't want to introduce an external package (for this). Want to keep the `formio` module as lean as possible.
3. Of course we need to keep the version naming the same as done in the `formio/formio.js` library (project).
Like you suggested, it would be possible to add a field just for the sorting and come up with a custom sorting code/solution.
Would be great to see a PR here!

**Comment by BT-jcolmeiro** [comment]
Hi @bobslee Great thank you! I will try to work on it.

Regarding using parse_version, you fixed it but then reintroduced it in your last commit:
https://github.com/novacode-nl/odoo-formio/commit/631228aca7d194c6c6c560a1cd4214ba71b0885b

maybe this was an error due to an outdated branch or is it done on purpose?

**Comment by bobslee** [comment]
Thanks @BT-jcolmeiro !
I really have no clue why this ended up.
But changed (fixed again) in latest commit now.

See also the comment:
https://github.com/novacode-nl/odoo-formio/commit/631228aca7d194c6c6c560a1cd4214ba71b0885b#r100588676

**Comment by bobslee** [comment]
@BT-jcolmeiro has this issue been solved, cleared out?
Can we close it?

**Comment by BT-jcolmeiro** [comment]
Yeah, it's been stable for a long time now. I can't close issues, so please go for it!

**Comment by bobslee** [comment]
Thanks for responding @BT-jcolmeiro !
