### ISSUE TITLE
formio_mail mail tab not visible in form builder

### ISSUE THREAD

**Issue by chjud** [novacode-nl/odoo-formio#291]
The Mail Tab does not appear when formio_mail is uploaded. The module itself is present, but no upgrade/update button visible either. Using V17.0

**Comment by bobslee** [comment]
@chjud The `formio_mail` module isn't installable.
See: https://github.com/novacode-nl/odoo-formio/blob/17.0/formio_mail/__manifest__.py#L25C5-L25C26

So why and how you tried to install?

**Comment by chjud** [comment]
I downloaded it from github and uploaded it to the server.
Unfortunately i have no programming skills, otherwise i would help sorry

**Comment by bobslee** [comment]
Sorry, the module is still flagged `installable: False` in the `__manifest__.py` file. 

This due to the module is not migrated from v14 onward. 

You could create an automated action (email) to accomplish the goal. 
We can offer support to get it done with our best practices and quickly.

I close this issue now.
