### ISSUE TITLE
error installing form.io reports generator Odoo v12

### ISSUE THREAD

**Issue by davidogles** [novacode-nl/odoo-formio#44]
Unable to install module "formio_data_api" because an external dependency is not met: No module named formiodata

**Comment by bobslee** [comment]
Did you install the Python dependency?

Execute as root user:
pip3 install formio-data

See it's documentation: https://github.com/novacode-nl/python-formio-data

**Comment by davidogles** [comment]
no I hadn't.  I installed and was able to install.  Thanks for the info.  

Also, is there any type of documentation regarding the report_qweb app.
thanks,
Dave

**Comment by bobslee** [comment]
Hi Dave,
You're welcome. 

There's no documentation because:
- the module ships 2 generic reports available under the "print" dropdown on every form. 
- those reports are extensible by Qweb inheritance. So you're able to change, override, improve (PR's are very welcome).

Do you need any particular info?

**Comment by davidogles** [comment]
thanks

**Comment by isaacbarnor** [comment]
Unable to install module "formio_data_api" because an external dependency is not met: 
I still get the error after installing formio-data module

**Comment by bobslee** [comment]
Hi, please provide more details, versions:
- OS (Ubuntu, Debian) version
- Odoo version
- formio (module) version
- formio_data_api (module) version

Is `formiodata` listed when running commandline: `pip3 freeze | grep formio`

Thanks!

**Comment by isaacbarnor** [comment]
formio-data==0.2.3 (when i run pip3 freeze | grep formio)
odoo14
formio_report_qweb-14.0.2.1 (I get the error when i am installing this app)
Ubuntu 20.04 LTS
This is the link I used to download the app. 
https://apps.odoo.com/apps/modules/14.0/formio_report_qweb/

The forms I was able to install, The report_qweb throws that error.
Thanks for your speedy response

**Comment by bobslee** [comment]
I reviewed this on a clean Ubuntu 20.04 server. See below how I could reproduce and it works.

Did you installed the `formio-data` library in the PYTHON_PATH of the `odoo` system/OS user?

**(1) Initial indeed the error due to missing Python requirement**

![image](https://user-images.githubusercontent.com/328803/111792722-ced58780-88c4-11eb-8d17-0c89f2b00a29.png)

**(2) After installing `formio-data` from PyPi**

![image](https://user-images.githubusercontent.com/328803/111792935-0a705180-88c5-11eb-888a-451783e50ebc.png)

**Comment by isaacbarnor** [comment]
Did you installed the formio-data library in the PYTHON_PATH of the odoo system/OS user?
As OS user. Dont' have access to root currently

**Comment by bobslee** [comment]
You need this in the PYTHON_PATH where Odoo can find its Python packages.
Are you on "odoo.sh" service?

**Comment by isaacbarnor** [comment]
Nope. this is an on-a local server . It is not on the odoo cloud or odoo.sh. 
So uninstalled the forms. Uninstalled the formio-data module.

Reinstalled it with sudo pip3 install formio-data. Successfully installed the forms again 
But I could not install the Forms QWeb Reports
anything else to try. Yes it is in the Python path where all the other python modules are installed /usr/local/lib/python3.8/dist-packages (0.2.3)
![image](https://user-images.githubusercontent.com/11571209/111810751-4360f400-88ce-11eb-8a54-dfffa078f9b7.png)

**Comment by bobslee** [comment]
Thanks for your extensive info!
Please can you edit the file (in module): `formio_data_api/__manifest__.py` ? 

Change to below, try and let me know whether it works:

```python
'external_dependencies': {
    'python': ['formiodata'],
}
```

Which show `formiodata` instead of `formio-data`.

**Comment by isaacbarnor** [comment]
![image](https://user-images.githubusercontent.com/11571209/111818936-a4d99080-88d7-11eb-898d-5d2da3e4f454.png)

Nope didn't work.
changed the manifest file. and restarted the odoo14.service.
tried to install again. same error msg

**Comment by bobslee** [comment]
That's unfortunately. I never got this error reported or experienced until now.
If you would like me to assist further you've to send me a mail: bob(at)novacode(dot)nl

Best!

**Comment by datahaulic** [comment]
Hi Bob,

I am having the same error in trying to install Forms | Data API and Forms | QWeb Reports on Odoo.sh instance. I executed pip3 install -U formio-data successfully, but still getting the error Unable to install module "formio_data_api" because an external dependency is not met: Python library not installed: formio-data.

Any ideas on how I can solve this?

Thanks in advance

**Comment by bobslee** [comment]
Hi @datahaulic ,
So you also use Odoo 12 ?

By the way, you also posted a question on Odoo Apps Store (formio)?

**Comment by datahaulic** [comment]
Hi Bob,
That was lightening fast :) Thank you very much for your response. Yes I did post earlier under the app store. I was able to get the Form Builder installed successfully after using a new database. I am using V14. And right after I post the last post I edited the formio_data_api/__manifest__.py file and used your recommended step

'external_dependencies': {
    'python': ['formiodata'],
}

and BOOM! I was able to complete the installation. I am new to the Form Builder but thus far it's proving to be a game changer. I am now trying to get the PDF export going. That you again for this tool and support. I did read that you guys are absolutely efficient and I am seeing that for myself.

I'll let me know if I run into any more challenges :)

Cheers

**Comment by bobslee** [comment]
Hi @datahaulic 
Thanks for your answer, and yes, daylight starts here in The Netherlands.

The issue you reported is rather odd, I regret.
Because I've some relations on **odoo.sh** too, which install without any hazzle and use the dependency as coded:

https://github.com/novacode-nl/odoo-formio/blob/14.0/formio_data_api/__manifest__.py#L16

Anyway, have a nice day!

**Comment by bobslee** [comment]
@datahaulic please could you leave a rating/review in on the Odoo Apss Store? Thanks!
https://apps.odoo.com/apps/modules/14.0/formio/

**Comment by datahaulic** [comment]
Hi Bob,

I have successfully installed and tested Formio 4.9.26 on a version 14 Odoo.sh instance. I am experiencing an issue exporting any Survey type question to PDF. Whenever I download a completed PDF form I am not seeing any data for those types of questions. 

Is this something you can offer any recommendation on?

Thanks in advance for your consideration.

Regards,
Curtis

Sent from Mail for Windows 10

**Comment by bobslee** [comment]
Hi, unfortunately the Survey component isn't implemented in the QWeb module yet. 

Of course you can implement yourself and submit a PR.
If you'd like me to implement, send me a mail so we can discuss the effort.

**Comment by datahaulic** [comment]
Hi Bob,

Thank you for your response. I am interested in getting it implemented. Kindly provide a quotation for efforts on same or let me know when we can discuss details further.

Kind Regards,
Curtis

Sent from Mail for Windows 10

**Comment by bobslee** [comment]
Hi Curtis,
Please send me mail to:

bob(at)novacode(dot)nl
