### ISSUE TITLE
[odoo13] formio public form: redirect isn't working

### ISSUE THREAD

**Issue by lieblinger** [novacode-nl/odoo-formio#60]
Setting up a redirect page in form builder settings isn't working. After submit public page isn't redirecting to specified page.

**Comment by bobslee** [comment]
@lieblinger this works for me, just tested on:
- https://demo13.novacode.nl
- webbrowsers: Firefox, iOS v13 Safari

Some questions could help to analyse:
- Please check the webdeveloper tools console for any errors (report here).
- Did you tried to clear your webbrowser cache?

Otherwise, please could you provide more info?
(which webbrowser, module version)

**Comment by bobslee** [comment]
@lieblinger does the issue still occur in latest release/version?
Seemed to work for me.
