### ISSUE TITLE
[odoo13] formio github: form.io versions >= 5 aren't working

### ISSUE THREAD

**Issue by lieblinger** [novacode-nl/odoo-formio#62]
If the downloaded form.io version equals or is bigger than 5.0, the form builder is showing only a white page.

**Comment by bobslee** [comment]
Affirmative @lieblinger 
Me too, had the same experience while testing this experience. 
We need to investigate what's going on.
Could the Formio library API be changed since version?

**Comment by bobslee** [comment]
@lieblinger luckily this issue has been fixed by a recent commit (Odoo 13, 12 tough)...
https://github.com/novacode-nl/odoo-formio/commit/7d9674a2d5c542421676149b32aaebd673fdb1d3#diff-ab6986dd0fd3af3bdb47f4c6a9543fa7102ef876912808f0b6617fb941b0b4d4R34

Maybe you could test? Otherwise, can I close this issue?

Latest Formio releases/versions seem to work now! `>=4.12.1`, `>=5.0.0-m.x`

From now on a Formio Builder object shall be instantied (contructor).
Seems they extended the highlevel AP, also metnoined e.g. https://github.com/formio/formio.js/issues/762#issuecomment-562892095

**Comment by bobslee** [comment]
Solved.
