### ISSUE TITLE
formio.js GitHub releases: obtaining the latest 30 release versions often get 403 errors

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#79]
It seems that the latest 30 versions of information cannot be obtained correctly. For example, 4.12.2-rc.3 cannot be obtained, and I feel that version 5.0 is not the latest version.

**Comment by bobslee** [comment]
@niulinlnc Indeed, I also experienced and developed a rather incomplete solution here. 
I was expecting such question :)

Use links below to obtain the tags and releases. You'll there no releases to be fetched, because there ain't published.
- tags: https://api.github.com/repos/formio/formio.js/tags
- releases: https://api.github.com/repos/formio/formio.js/releases

Indeed, the GitHub tags API only returns the latest 30 tags, which is rather annoying.
Maybe you/somebody could come up with an idea how to solve this? Let's discuss first.

**Important:**
Fetching the releases or tags has been implemented straight on the GitHub API, with Python `requests` library.
I don't want to introduce an extra Python (github) dependency to support this feature.

**Code which actually fetches the latest releases:**
https://github.com/novacode-nl/odoo-formio/blob/13.0/formio/wizard/formio_version_github_checker_wizard.py#L24

**Comment by niulinlnc** [comment]
@bobslee I can indeed get the latest version through https://api.github.com/repos/formio/formio.js/tags, but not in the first line. So this problem should not be a problem anymore. There is another problem. 403 errors often occur when getting tags through api. It seems to be restricted, and tokens need to be provided to improve. So I think we should add a github personal access token value. probably modify as follows:
token = self.env['ir.config_parameter'].sudo().get_param('formio.default_github_personal_access_token')
res = []
headers = {"Authorization": token}
response = requests.get('https://api.github.com/repos/formio/formio.js/tags', headers=headers)

**Comment by bobslee** [comment]
@niulinlnc So basically you mean there's no issue with getting versions? 30 latest versions are OK ?

Thanks for the heads up, regarding the 403 errors, and access_token solution!
You're prepping a PR for this?

**Comment by niulinlnc** [comment]
@bobslee I will post a fix later.

**Comment by bobslee** [comment]
@niulinlnc Excellent !

Please implement accordingly:

**(1) Access token shouldn't be mandatory**
Users maybe won't configure this in the first place.

**(2) res.config.settings**
Add the setting/param `formio.default_github_personal_access_token' `into `res.config.settings` (and view).
Also add some helptext (in view below) to explain why... it solves the HTTP 403 (GitHub) errors.

- model: https://github.com/novacode-nl/odoo-formio/blob/13.0/formio/models/res_config_settings.py
- view: https://github.com/novacode-nl/odoo-formio/blob/13.0/formio/views/res_config_settings_views.xml

**Comment by niulinlnc** [comment]
@bobslee [https://github.com/novacode-nl/odoo-formio/pull/85](url)

**Comment by bobslee** [comment]
Done, merged PR https://github.com/novacode-nl/odoo-formio/pull/85
