### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by onmywaytoheaven** [novacode-nl/odoo-formio#8]
Hello

I have some issues with creating form in Russian. For example, I cant change some buttons display name ("Previous", "Next", "Cancel" in Wizard mode).
Steps:
1) In "Configuration" -> "Translations" create translation for language Russian (for button Next in pic) ![изображение](https://user-images.githubusercontent.com/43062804/64321674-af6c5780-cfc9-11e9-97cc-a956160e724e.png)
2) Create new Wizard-form in Form Builders page
3) Open form in builder. Add new page
4) Assign to user
5) Open form as user.

**Expected:**
"Next" button translated to Russian
**What i got:**
Nothing

![изображение](https://user-images.githubusercontent.com/43062804/64322465-4be32980-cfcb-11e9-8b2f-61cff7d25ad7.png)

Looks like English language is a default for now. Is it possible to change default Form language? May be this feature could help

Thank you for your work!

P.S. I hope that you are not tired of my issues. If this problem related to formio library I wll open issue on their github page

**Comment by bobslee** [comment]
Could you please try to change the propertyname to "nextPage" ?
Maybe that could work. Plese let me know :)

The form language is set, either by:
- Active (session) language from the Odoo Website
- Else, the language of logged in user. One can change the language in the account preferences.

I still need to experiment with lots of Form.io functionalities too. So I guess, there're things which won't function like expected. Because the full-blown Form.io (JS) client is loaded into Odoo.

On the contrary, your reviewing and reports are much appreciated!
Thanks again!

**Comment by onmywaytoheaven** [comment]
I tried to change nextPage, but it doesnt help.

What i observe:
I have user with russian language. I created form with just one element in Russian language. I tried to translate some elements into English with "Translations" tab in Form Builder
![изображение](https://user-images.githubusercontent.com/43062804/64324756-9d8db300-cfcf-11e9-85ca-6306aea1ffaa.png)
But when i opened form as user i got this:
![изображение](https://user-images.githubusercontent.com/43062804/64324818-ba29eb00-cfcf-11e9-95a9-0e051d072948.png)
As you see there is no language switcher and buttons are in lowercase - as I think this is a sign, that form is in Russian language (because when it in English - buttons names starts with uppercase letter)

And if I add the some wierd translation, but choose Russian language (pic related) 
![изображение](https://user-images.githubusercontent.com/43062804/64325978-cdd65100-cfd1-11e9-9a1d-969fb64df8a4.png)
The language switch appears, and the translation starts working correctly
![formio_translate](https://user-images.githubusercontent.com/43062804/64326453-acc23000-cfd2-11e9-84f6-63dc8cba7193.gif)

**Comment by bobslee** [comment]
#### Regarding the translation of the "Form.io GUI buttons" like "nextPage"

I also don't know how to accomplish. 
I'm sorry, please head over to the Form.io project - suggestions:
- Check the examples https://formio.github.io/formio.js/app/examples/
- Check the Wiki: https://github.com/formio/formio.js/wiki
- Otherwise, again submit this question on https://github.com/formio/formio.js/issues

#### Regarding translations of your Form design

Hhm ok, a case I didn't tried yet  ;)

Please could you try to design the form completely in English?
Then translate the English tems to Russian.

**Comment by onmywaytoheaven** [comment]
If I try to translate from English to Russian, then everything works as it should

Regarding the translation of the "Form.io GUI buttons" - I can translate it with form translation
![изображение](https://user-images.githubusercontent.com/43062804/64328708-9fa74000-cfd6-11e9-96d5-05f929d3f360.png)

It works well
![formio_translate1](https://user-images.githubusercontent.com/43062804/64328810-d0877500-cfd6-11e9-8f58-bdb4b138ecc8.gif)

**Comment by bobslee** [comment]
Hi, that looks awesome!

Could you please translate the "Next" button, in both:
- Settings / Translations (**property** : "next"
- Form Builder / Translations (**Soure term** : "next")

("next" => lowercase)

**Comment by onmywaytoheaven** [comment]
It work only if i translate in Form Builder -> Translations

**Comment by bobslee** [comment]
Ok, nice to read!

Let me elaborate more about the 2 translations windows (listed by menu path below).

**Form Builder > Translations:**
For all added form components its properties (labels, buttons, selection options). So the translations of your custom designed components.

**Settings > Translations:**
Form.io GUI / API translations. So translations of the Form.io JS library its translatable terms.

Hope my answer seems logical.

**Comment by bobslee** [comment]
By the way. It would be awesome if we could implement an action (behind new button "Validate") on the Form Builder, which checks all translateble terms in all components.

**This should result in the following:**
- Add a tanslation record for new (found) terms. The "Translation value" should still be empty upon creation of the record.
- Mark or remove obsolete Translations. Obsoleteness of Translations are where no "Source term" can be found in the translateble Builder components.

First we need to develop a parser for the Form Builder schema. The parser shall generate and offer an easy to use data/object structure, or even better, all translateble terms.
I already started with that kind of parser (in Python), but I'm in a lack of time since. Feel free to contribute tough :)

https://github.com/novacode-nl/python-formio-parser

**Comment by bobslee** [comment]
@onmywaytoheaven is my explanation satisfying enough for you?
So we can close this issue ;-)

**Comment by onmywaytoheaven** [comment]
Yeah, thank you!
