### ISSUE TITLE
[14.0] After installing formio_sale, I create a form for a sale, but the content is empty.

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#95]
@bobslee Pls see below for comparison:
![无标题13](https://user-images.githubusercontent.com/11767049/101736194-fb2b7c00-3afd-11eb-88a6-a5c7d07ae12d.jpg)
![无标题](https://user-images.githubusercontent.com/11767049/101736203-01215d00-3afe-11eb-819b-8945da7b577f.jpg)

**Comment by bobslee** [comment]
Thanks for reporting. I'll try to analyse/fix upcoming days.

**Comment by bobslee** [comment]
@niulinlnc I reproduced the issue and finally solved on my local development env. 

Issue is due to formatting the language code with an underscore "_", whereas the Formio JS implementation expects a hyphen "-". 

Before I push the change, I improve the code and shall test again. 

This is also related to #93

**Comment by bobslee** [comment]
@niulinlnc Issue should be solved now.
Please download and upgrade to `formio` version 8.3. Clear your webbrowser cache too.
Let me know if any further issues regarding translations and language switcher.

**Comment by bobslee** [comment]
@niulinlnc please could you review and close issue?
I fixed and tested on version 14.0
